create table people (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    name varchar(30) not null,
    created_at timestamp default systimestamp,
    updated_at timestamp default systimestamp
);

CREATE OR REPLACE TRIGGER updated_at_timestamp
  BEFORE UPDATE ON people
  FOR EACH ROW
BEGIN
  :new.updated_at := systimestamp;
END;
/


